name: Parallel Processing1

on:
  push:
    branches:
      - main

jobs:
  process_files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - file1
          - file2
          - file3
          - file4
          - file5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process File
        run: |
          # Replace this command with the actual command to process your file
          echo "Processing ${{ matrix.file }}"
