name: Parallel Processing

on:
  push:
    branches:
      - main

jobs:
  process_files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{fromJson(secrets.INPUT_FILES)}}

    outputs:
      file-output: ${{ matrix.file }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process File
        id: process
        run: |
          # Replace this command with the actual command to process your file
          output=$(echo "Processing ${{ matrix.file }}")
          echo "::set-output name=output::$output"

      - name: Store Output
        run: |
          # You can use the output in this step or store it for future use
          echo "Output: ${{ steps.process.outputs.output }}"
