on: push

jobs:
  process_inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get number of inputs
        id: get_inputs
        run: |
          INPUTS=$(ls inputs | wc -l)
          echo "::set-output name=num_inputs::$INPUTS"
      - name: Process inputs
        id: process_inputs
        run: |
          for input in inputs/*
          do
            job="process_${{ github.sha }}_$(basename $input)"
            echo "::group::$job"
            echo "::endgroup::"
          done

${{ steps.get_inputs.outputs.num_inputs }}

jobs:
${{ fromJSON(steps.process_inputs.outputs.result) }}
  process_%job%:
    needs: process_inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process %job%
        run: |
          # Process input file %job%
          outputfile=%job%-output
          
          # Generate output file
          echo "Output" > $outputfile
        
      - uses: actions/upload-artifact@%v2
        with:
          name: %job%-output
          path: $outputfile
