name: Process Files

on:
  push: 
    branches: [main]

jobs:

  read_config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: read  
      run: |
        echo ::set-output name=num::$(cat num_files.txt)
        
  process_files:

    needs: read_config
    
    runs-on: ubuntu-latest

    strategy:
      max-parallel: ${{fromJson(needs.read_config.outputs.num)}}
      matrix: 
        file: [${{ fromJson(join(range(fromJson(needs.read_config.outputs.num)))) }}]
    
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Process files
        id: process
        run: |
          echo "Processing file ${{ matrix.file }}"
          echo "Output of file ${{ matrix.file }}" >> outputs.txt
          echo ::set-output name=out::$(cat outputs.txt)
          
      - name: Print outputs  
        run: |
          echo "All outputs:"  
          cat outputs.txt
