name: Parallel Jobs Example

on:
  push:
    branches:
      - main

jobs:
  run_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - file1.txt
          - file2.txt
          - file3.txt
          - file4.txt
          - file5.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Job
        run: |
          echo "Running Job with file: ${{ matrix.file }}"
          # Add your commands for each job with ${{ matrix.file }} here
